# Generated by Django 3.2.14 on 2022-08-06 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEntrega', models.CharField(max_length=50)),
                ('observacao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrgaoDonatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('horarioFuncionamento', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrgaoFiscalizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=50)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front_ent_SemFraude.lote')),
            ],
        ),
        migrations.AddField(
            model_name='lote',
            name='orgaoDonatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front_ent_SemFraude.orgaodonatario'),
        ),
        migrations.AddField(
            model_name='lote',
            name='orgaoFiscalizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front_ent_SemFraude.orgaofiscalizador'),
        ),
    ]
